### ISSUE TITLE
GLB 3D model fails to import correctly

### ISSUE THREAD

**Issue by robl80** [microsoft/glTF-SDK#102]
There appears to be an issue with the glb import of an octopus 3d model from sketchfab.com.

Please download the GLB 3d model from here: https://skfb.ly/opvx9 (This is a short link for the octopus 3d model on sketchfab.com https://sketchfab.com/3d-models/octopus-14a73529b33d48d9990d030896c67028)

The 3d model imports correctly in Blender and the online GTLF viewer: https://github.khronos.org/glTF-Sample-Viewer-Release/

In the Microsoft GLTF library, use the `GLBResourceReader` to import the 3d model.

I'm unsure if there is an issue in the json returned from `GLBResourceReader::GetJson()`

Specifically, search for the part that starts Bone001|Unreal Take|...

```
"name": "Bone001|Unreal Take|Base Layer Retarget",
            "samplers": [
                {
                    "input": 7,
                    "interpolation": "LINEAR",
                    "output": 8
                },
                {
                    "input": 7,
                    "interpolation": "LINEAR",
                    "output": 9
                },
```

All inputs refer to 7. However, the json file retrieved from the octopus 3d model in GLTF format has incremental values for the input of each sampler.

Not sure if this is the reason for the failed animation. The static 3d model imports correctly.

Using the GLTFResourceReader the 3d model of the octopus animates in exactly the same way as shown in the sketchfab.com site.

Please let me know if you can see an issue in the GLTF library or the GLB 3d model.

**Comment by bghgary** [comment]
Sorry, I was out the last two weeks. Did you resolve this?
