### ISSUE TITLE
Exceptions necessary ?

### ISSUE THREAD

**Issue by jimver04** [microsoft/glTF-SDK#106]
Are these exceptions necessary? They are always stopping the code. It works perfect without them

1) \GLTFSDK\Source\BufferBuilder.cpp

```
if (desc.byteOffset % componentTypeSize != 0)     
{       
    throw InvalidGLTFException("asccessor offset within buffer view must be a multiple of the component size");  
 }


if ((desc.byteOffset + bufferView.byteOffset) % componentTypeSize != 0)
{
    throw InvalidGLTFException("accessor offset within buffer must be a multiple of the component size");
 }

```

desc is just a description of the accessor like this

`{ Microsoft::glTF::TYPE_VEC3, Microsoft::glTF::COMPONENT_FLOAT, false, std::move(minValues), std::move(maxValues) }`

why has to be divided by float size 

`size_t componentTypeSize = Microsoft::glTF::Accessor::GetComponentTypeSize(accessorDesc.componentType);`
?

2) \GLTFSDK\Source\ResourceWriter.cpp

```

    // From the glTF 2.0 spec: the offset of an accessor into a bufferView (accessor.byteOffset) must be a multiple of the size of the accessor's component type
    if (accessor.byteOffset % componentTypeSize)
    {
        throw InvalidGLTFException("accessor.byteOffset must be a multiple of the accessor's component type size");
    }


    // From the glTF 2.0 spec: the offset of an accessor into a buffer (accessor.byteOffset + bufferView.byteOffset) must be a multiple of the size of the accessor's component type
    if ((accessor.byteOffset + bufferView.byteOffset) % componentTypeSize)
    {
       throw InvalidGLTFException("accessor.byteOffset + bufferView.byteOffset must be a multiple of the accessor's component type size");
    }
```

???

**Comment by bghgary** [comment]
This is per the specification. It is necessary for fast loading on the web IIRC due to alignment requirements of JS array buffers.

**Comment by bghgary** [comment]
See here: https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#data-alignment
