### ISSUE TITLE
ByteOffset should be a multiple of 4 in Javascript

### ISSUE THREAD

**Issue by jimver04** [microsoft/glTF-SDK#109]
Hi, 

I am trying to load the exported glb in other engines such as Three.js. 
In Javascript, there is an issue when the byteOffset is not a multiply of 4: https://stackoverflow.com/questions/15417310/why-typed-array-constructors-require-offset-to-be-multiple-of-underlying-type-si 

GLTFSDK exports everything in a single buffer, e.g. indices (2 bytes per indice, i.e. Int16) and vertices (12 bytes per vertice = 3 floats32). 

This is an issue because if you have odd number of triangles
 1 triangle = 6 bytes offset
 3 triangles = 18 bytesOffset
 5 triangles = 30 bytesOffset,

they can not be loaded. For example if you have a single triangle, you should have a byteOffset of 6 bytes (3 indices * 2 bytes), and then have the vertices next. However a byteOffset can not be 6 because it is not a multiply of 4.

I think you shouldn't mix indices and vertices in the same buffer. 

Best,
Dimitrios

**Comment by bghgary** [comment]
Can you provide an example?

**Comment by jimver04** [comment]
Let us assume that we have only one triangle  :)

Indices = [0, 1, 2] = [2 bytes, 2 bytes, 2 bytes]
vertices = [[0.0, 1.0, 0.0], [1.0, 1.0, 1.0], [1.0, 0.0, 0.0] = [[4 bytes, 4 bytes, 4 bytes], [4 bytes, 4 bytes, 4 bytes], [4 bytes, 4 bytes, 4 bytes]]

Then your SDK generates the following buffer to store the above information

buffer = [ 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4]  bytes

where the first 3 positions are used to store the indices and the rest the vertices. Javascript doesn't like that because the offset for vertices is 6 which is not a multiply of 4.

It would like to have another 2 bytes of dummy data to intervene before vertices, i.e.

[ 2, 2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4]

or for me is better to use separate buffers within the GLB

buffer1 = [2, 2, 2]
buffer2 = [4, 4, 4, 4, 4, 4, 4, 4, 4]

Best,
Dimitrios

**Comment by jimver04** [comment]
Also, in the above example I have assumed that you store indices as Uint16, which is not the case as I see you store them in Uint32, namely four bytes. 
Unfortunately Three.js stores them as Uint16 and this is an issue. Khronos should be more strict in this topic. See also the issue I have opened in Three.js : https://discourse.threejs.org/t/gltf-maximum-buffer-size-for-vertices-65536-is-too-low/44720

**Comment by jimver04** [comment]
Actually, do you store indices with 4 bytes ? When I parse the glb, I see that you use only 2 bytes for indices which is incosistent as you have big buffers for the vertices.
