### ISSUE TITLE
Point size and Line width

### ISSUE THREAD

**Issue by jimver04** [microsoft/glTF-SDK#129]
Hi, 

in 

mesh.primitives.mode = MESH_POINTS;
mesh.primitives.mode = MESH_LINES;

can we configure the size of the points and the lines ? Sometimes the model may be too big and if the points have a constant small size, they will be invisible from distance. Can the size adapt to the bounding box of the model ?

Best,
Dimitrios

**Comment by bghgary** [comment]
This probably should go in the [glTF repo](https://github.com/KhronosGroup/glTF/tree/main/specification/2.0) and not here, but since I know this off the top of my head.

https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#point-and-line-materials
> Points and Lines SHOULD have widths of 1px in viewport space.
