### ISSUE TITLE
Some valid GLBs failed to load with an exception

### ISSUE THREAD

**Issue by bghgary** [Microsoft/glTF-SDK#13]
See https://github.com/KhronosGroup/glTF-Blender-IO/issues/61#issuecomment-435994547

The issue is from this line in the code:

https://github.com/Microsoft/glTF-SDK/blob/master/GLTFSDK/Source/GLBResourceReader.cpp#L141

> if (length <= (jsonChunkLength + GLB_HEADER_BYTE_SIZE))

should be

> if (length < (jsonChunkLength + GLB_HEADER_BYTE_SIZE))

Here is a file that causes this issue:
[_io_2_8_cube.zip](https://github.com/Microsoft/glTF-SDK/files/2550813/_io_2_8_cube.zip)

The exception is:
> File length 4848 less than content length 4828 plus header length 20

**Comment by agrittmsft** [comment]
Fixed in https://github.com/Microsoft/glTF-SDK/pull/17

Cheers

**Comment by agrittmsft** [comment]
Checked into master.
