### ISSUE TITLE
Validation fails when using Draco with no fallback

### ISSUE THREAD

**Issue by MiiBond** [Microsoft/glTF-SDK#15]
When using Draco compression as a required extension, the validator complains that my accessors for the uncompressed data are invalid because they don't have bufferViews. 

`throw ValidationException("Non-Sparse Accessor " + accessor.id + ": does not have a bufferView");`

However, according to the Draco extension spec, they should not have bufferViews defined.

[draco_test.zip](https://github.com/Microsoft/glTF-SDK/files/2563836/draco_test.zip)

**Comment by agrittmsft** [comment]
Should be fixed in https://github.com/Microsoft/glTF-SDK/pull/16

Cheers

**Comment by agrittmsft** [comment]
Checked into master.
