### ISSUE TITLE
Accessor min+max should have double precision

### ISSUE THREAD

**Issue by agrittmsft** [microsoft/glTF-SDK#18]
Accessor min+max should have double precision instead of float, since JSON numbers have an arbitrary level of precision that is higher than float.

**Comment by JeanPhilippeKernel** [comment]
Can I take it ? , how I can work on it ?

**Comment by donno** [comment]
Is this issue valid?  For glTF 2.0, based on the following paragraph from the specification it seems it isn't.

> accessor.min and accessor.max properties are arrays that contain per-component minimum and maximum values, respectively. Exporters and loaders must treat these values as having the same data type as accessor's componentType, i.e., use integers (JSON number without fractional part) for integer types and use floating-point decimals for 5126 (FLOAT). - [Reference](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0)

The implementation note that follows also mentions in JavaScript the recommendation is to round to the nearest 32-bit single precision float .

**Comment by bghgary** [comment]
I tend to agree. This doesn't seem like something we should support.
