### ISSUE TITLE
Write primitive with more than 65535 vertices

### ISSUE THREAD

**Issue by luizcarlosfx** [Microsoft/glTF-SDK#35]
When I set the accessor component type to COMPONENT_UNSIGNED_INT I get an error when serializing:

    ComponentType indexType = (verts.size() / 3) <= USHRT_MAX ? COMPONENT_UNSIGNED_SHORT : COMPONENT_UNSIGNED_INT;
    string trisId = bufferBuilder.AddAccessor(tris, { TYPE_SCALAR, indexType }).id; // error on this line

**Comment by chriche-ms** [comment]
What exactly do you mean by 'error'? Is it failing to compile, throwing an exception or crashing? If an exception is being thrown what is the exception type and message (a callstack with line numbers would be very useful)?

Based on your code snippet I'm guessing you are passing a std::vector<unsigned short> but specifying COMPONENT_UNSIGNED_INT. There isn't any explicit check to ensure the buffer's data type matches the accessor's ComponentType but it will likely result in some sort of size mismatch exception being generated while writing the accessor data.

**Comment by luizcarlosfx** [comment]
> What exactly do you mean by 'error'? Is it failing to compile, throwing an exception or crashing? If an exception is being thrown what is the exception type and message (a callstack with line numbers would be very useful)?
It throws an exception in StreamUtils line 43
> 
> Based on your code snippet I'm guessing you are passing a `std::vector<unsigned short>` but specifying COMPONENT_UNSIGNED_INT. There isn't any explicit check to ensure the buffer's data type matches the accessor's ComponentType but it will likely result in some sort of size mismatch exception being generated while writing the accessor data.
You're write, I was passing an std::vector<unsigned short>, I was pretty sure it was an std::vector<unsigned int>. It's working now,

**Comment by luizcarlosfx** [comment]
I don't know if this is the right place to leave this question, but, Is there any drawback of always using 32bit indices? I deal with many meshes with more than 65k verts. Is there any advantage of using some 16bit meshes and other 32?
