### ISSUE TITLE
Update glTF 1.0 Deserialize Unit Tests

### ISSUE THREAD

**Issue by chriche-ms** [Microsoft/glTF-SDK#37]
The following test inputs are using the 1.0 spec!

c_negativeAccessorOffset
c_negativeAccessorCount
c_negativeBufferLength
c_negativeBufferViewOffset
c_negativeBufferViewLength
c_invalidAccessorComponentType

The tests need rewriting so that:

1. The test input is written against the 2.0 spec
2. The tests need an assert adding, one that checks that the throw exception's message matches the known schema violation in the input manifest.

Consider also adding at least one assert for the following tests or test inputs:

c_extraFieldsJson
SerializerGLTFTests_InvalidDefaultScene
c_validPrimitiveNoIndices
c_invalidPrimitiveAccessorComponentType
c_invalidPrimitiveAccessorType

**Comment by wangdemon** [comment]
This library doesn't seem to support version 1.0. How do you parse gltf of version 1.0?

**Comment by bghgary** [comment]
I don't think there is support for 1.0. Why do you need this?
