### ISSUE TITLE
Example code for the Microsoft.glTF.CPP nuget package is out of date

### ISSUE THREAD

**Issue by stevk** [microsoft/glTF-SDK#42]
Example code is found under the Documentation section.
https://www.nuget.org/packages/Microsoft.glTF.CPP/#

Specifically this line:
`GLTFDocument gltfDoc = DeserializeJson(json);`
Which I'm pretty sure should be:
`Document gltfDoc = Deserialize(json);`

There might be other issues as well.

**Comment by agrittmsft** [comment]
Hi @stevk - you are correct about the change in the code, in the latest version this would be just "Document". However I believe the documentation on nuget.org is correct for _that_ version (v1.6.3.1) - we stopped releasing NuGet packages 10 months ago in favour of GitHub releases, which are now on r1.9.3.0.

I wasn't able to find documentation referencing "GLTFDocument" in this repository.

**Comment by stevk** [comment]
@agrittmsft That's good to know. I thought I was using the nuget package and had not downloaded anything from git, but maybe the code wasn't being referenced how I thought it was. I'll see if I can make some time to put together an example.

**Comment by stevk** [comment]
@agrittmsft I've made an example repro: https://github.com/stevk/glTF-Sample

**Comment by agrittmsft** [comment]
@stevk you are using an old branch (v1.6.x) of glTF-SDK which we don't plan on updating. Are you able to repro any issues with the latest version (v1.9.3)?

**Comment by stevk** [comment]
The issues detailed in my opening comment reproduce in the latest version (v1.9.3).

But that's aside from the point. The problem isn't with the glTF-SDK code, but with the example code included in the description of that nuget package.

**Comment by agrittmsft** [comment]
@stevk I only see an issue with the documentation in your opening comment, could you clarify what the problem with 1.9.3 is?

We'll see if we can update the NuGet documentation/URL without doing a re-release of the package.

**Comment by stevk** [comment]
@agrittmsft That is correct, the only issue is with the documentation. I was pointing out that `GLTFDocument` and `DeserializeJson()` are not valid (and are not expected to be) in either the old branch (v1.6.x) or in the latest version (v1.9.3).

**Comment by agrittmsft** [comment]
We have updated the documentation on NuGet.org: https://www.nuget.org/packages/Microsoft.glTF.CPP/#
