### ISSUE TITLE
Website link for theMicrosoft.glTF.CPP nuget package points at a generic Microsoft Mixed Reality page

### ISSUE THREAD

**Issue by stevk** [microsoft/glTF-SDK#43]
https://www.nuget.org/packages/Microsoft.glTF.CPP/#

Link under the "Info" section is https://aka.ms/Y8fymc, which points to https://developer.microsoft.com/en-us/mixed-reality

The target should be https://github.com/microsoft/glTF-SDK

**Comment by agrittmsft** [comment]
It doesn't seem to be possible to change this, as it's defined when the package is made. See here for v1.6.3.1:

https://github.com/microsoft/glTF-SDK/blob/93b985f0b3ca360e7daff3f404230142fa8dcaff/GLTFSDK/GLTFSDK.CPP.autopkg

**Comment by agrittmsft** [comment]
I was able to add the following text to the documentation on nuget.org:

**NOTE: This package is outdated, please go to https://github.com/microsoft/glTF-SDK to download the latest source code.**
