### ISSUE TITLE
How  to build  solution ? some contribution rules to follow ?

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [microsoft/glTF-SDK#44]

**Comment by agrittmsft** [comment]
Hi @JeanPhilippeKernel 

Solution file is here, if you have any specific issues with it, let us know: https://github.com/microsoft/glTF-SDK/blob/master/GLTFSDK.sln

Contribution guidelines are here: https://github.com/microsoft/glTF-SDK#contributing

Thanks!
