### ISSUE TITLE
Why Have you stopped building Nuget packages? And why does the readme still reference them?

### ISSUE THREAD

**Issue by ddayptc** [microsoft/glTF-SDK#45]

**Comment by agrittmsft** [comment]
We stopped releasing NuGet packages publicly because there is a internal code signing process that is hard for us to automate.

The readme should be updated.

**Comment by ddayptc** [comment]
Thank you for the response.  I figured it would be something like that.  Having code released with a Microsoft signed key seems like a business risk.
