### ISSUE TITLE
Add support of embedded images and buffers when writing

### ISSUE THREAD

**Issue by loic-jourdan** [microsoft/glTF-SDK#49]
The support of embedded images and buffers as base64 at write time is missing. Working around this is very tricky.
Doesn't embedding resources the most common method of generating gltfs?

**Comment by agrittmsft** [comment]
Hi @loic-jourdan - If you just want to embed everything in a single file then GLB would be a good option that glTF-SDK supports.

I would not recommend writing out base64 encoded glTF as it's both slower and somewhat space-inefficient. If you really want to do it anyway, in theory it should be possible to construct these kind of files with glTF-SDK, if you use another library to do the encoding.

**Comment by loic-jourdan** [comment]
This makes perfect sense, thank you for precision.
