### ISSUE TITLE
Support KHR_materials_common extension

### ISSUE THREAD

**Issue by o-oppang** [microsoft/glTF-SDK#50]
How about support KHR_materials_common extension in glTF-SDK in ExtensionsKHR?

I know glTF is based on PBR. However, it would be batter to support classic common materials(KHR_materials_common) as well. I am implementing and using an extension handler myself. However, It would be better that glft-sdk provide KHR_materials_common handler. Please review it.

https://github.com/KhronosGroup/glTF/tree/master/extensions/1.0/Khronos/KHR_materials_common

**Comment by chriche-ms** [comment]
The KHR_materials_common extension is only specified for version 1.0 glTF models, which are not supported by this library. We only intended to add support to the SDK for finalized 2.0 KHR extensions.

**Comment by o-oppang** [comment]
> The KHR_materials_common extension is only specified for version 1.0 glTF models, which are not supported by this library. We only intended to add support to the SDK for finalized 2.0 KHR extensions.

I got it completely. I will close this issue! Thank you to review it
