### ISSUE TITLE
Missing includes

### ISSUE THREAD

**Issue by donno** [microsoft/glTF-SDK#53]
There are several #include missing through out the project.

- [ ] Math.cpp needs `<tuple>` for `std::tie`
- [ ] GLTF.h needs `<algorithm>` for `std::all_of`
- [ ] GLBResourceReader.cpp needs `<string.h>` for `memcpy` and `strncmp`.

**Comment by bghgary** [comment]
Do you mind opening a PR?

**Comment by donno** [comment]
I don't mind, I've opened #54

**Comment by bghgary** [comment]
Landed in https://github.com/microsoft/glTF-SDK/commit/8d12da1079b4a1199e342689880c5d73f0e16eb2
