### ISSUE TITLE
After CMake the solution, CMake-project's building process appears a BUG

### ISSUE THREAD

**Issue by 674019130** [microsoft/glTF-SDK#58]
My step:
1. download glTF-SDK-master.
2. CMake the glTF-SDK-master.
3. open the project, and building it.
4. there's a BUG that called `error MSB6006: “cmd.exe” has exited，with code 1`

I wonder whether I need to install the SDK by [this](https://gltfsdk.visualstudio.com/build/_build/results?buildId=152&view=logs&j=fb588ed1-7636-53aa-446c-62c8592ab38e).
I am a rookie about this, plz tell me how to install it.

thx :-)

**Comment by bghgary** [comment]
Can you use the [solution file](https://github.com/microsoft/glTF-SDK/blob/master/GLTFSDK.sln) instead?

**Comment by bghgary** [comment]
If you want to use cmake, can you post the error log? The error you provided just means some command failed.

**Comment by 674019130** [comment]
> If you want to use cmake, can you post the error log? The error you provided just means some command failed.

Thanks for your reply, and I have solved this problem after using cmd to build the project.
There's a BUG cause my build path has a blank, CMake can not recognize the right path. I delete the blank in the folder path, then I build the project successfully and got the .lib file.

Thanks for your reply again, have a good day. :-)
