### ISSUE TITLE
Code samples request

### ISSUE THREAD

**Issue by sazonoff** [Microsoft/glTF-SDK#6]
Good day,
Are there any code samples/documentation available, how to work with SDK? For example, how to create a glTF::Document with mesh.

**Comment by agrittmsft** [comment]
Thanks for posting this issue @sazonoff it's definitely on our radar to write some clean samples. We will get back to you when we have some.

**Comment by sazonoff** [comment]
Please, don't forget samples, how to write single .glb file. Because it's not clear enough from source code, how to use GLB/GLTF writers. And example, how to write to a single .gltf file (with base64 encoded buffers).

**Comment by najadojo** [comment]
@sazonoff I think that the [glTF-Toolkit](https://github.com/Microsoft/glTF-Toolkit/) might give you some understanding of SDK usage.

**Comment by chriche-ms** [comment]
@sazonoff We are nearly finished writing deserialize and serialize sample apps (just need to make a few small changes). You can find the in-progress code at: https://github.com/Microsoft/glTF-SDK/tree/agritt/samples/GLTFSDK.Samples

We only have support for decoding base64 data URIs at the moment. Please make a separate issue if you would like encode support adding to the SDK.

**Comment by chriche-ms** [comment]
I've created a PR for the samples (https://github.com/Microsoft/glTF-SDK/pull/12). Feel free to add comments to the PR if any part of the sample code is unclear.

**Comment by agrittmsft** [comment]
Closing this. Please create another issue if there is something else we should cover in samples.

**Comment by ifcquery** [comment]
Is it possible with glTF-SDK to serialize a mesh with a data URI? 
Or only to de-serialize?
