### ISSUE TITLE
Using Webp with glb File

### ISSUE THREAD

**Issue by kitkat730** [microsoft/glTF-SDK#67]
How to use webp in glb. I don't understand properly from here.
[https://github.com/KhronosGroup/glTF/tree/master/extensions/2.0/Vendor/EXT_texture_webp#ext_texture_webp](url)

```
"textures": [
    {
        "extensions": {
            "EXT_texture_webp": {
                "source": 1
            }
        }
    }
]
```
I have already created a simple .glb file with png images but now want to use .webp instead of .png.
and also don't know how to add **EXT_texture_webp** extension using this SDK.  
Anyone Explain How to do it .
I appreciate your help very much!

**Comment by bghgary** [comment]
The relevant code bits are here:
- https://github.com/microsoft/glTF-SDK/blob/master/GLTFSDK/Inc/GLTFSDK/Extension.h
- https://github.com/microsoft/glTF-SDK/blob/master/GLTFSDK/Inc/GLTFSDK/ExtensionHandlers.h
- https://github.com/microsoft/glTF-SDK/blob/master/GLTFSDK/Inc/GLTFSDK/ExtensionsKHR.h

I unfortunately don't know how to do this well either, but I hope this will get you started.
