### ISSUE TITLE
Does not compile with newest version of Microsoft Visual Studio Community 2019 Version 16.8.3

### ISSUE THREAD

**Issue by ifcquery** [microsoft/glTF-SDK#71]
glTF-SDK\GLTFSDK\Source\SchemaValidation.cpp(37,1): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'Microsoft::glTF::rapidjson::SchemaDocument'

Does anyone have a solution for this?
Or is anyone able to compile this library with Visual studio?

**Comment by bghgary** [comment]
If you take out the last 3 parameters of that line, the GLTFSDK project will build.
```c++
            auto result = schemaDocuments.emplace(uri, rapidjson::SchemaDocument(document));
```

**Comment by ifcquery** [comment]
Thanks a lot, it works!
