### ISSUE TITLE
Examples of Serializing existing mesh

### ISSUE THREAD

**Issue by MariaShyn** [microsoft/glTF-SDK#91]
Hi,
I checked your example of how to serialize 1 triangle. Do you have any documentation on how to create a gltf/glb mesh with more than 1 triangle and probably how to convert an existing mesh (I have mine in STL format) with facets and nodes correspondences. 
Thanks!

**Comment by bghgary** [comment]
You can maybe look here for more complex scenarios: https://github.com/BabylonJS/BabylonPolymorph/tree/master/Morphs/Importers/Transcoders/Transcoders/Source, which also includes code to convert from STL to glTF.

**Comment by MariaShyn** [comment]
will check it out, thanks!
