### ISSUE TITLE
glft-sdk build failures with latest rapidjson on macOS

### ISSUE THREAD

**Issue by PhoebeHui** [microsoft/glTF-SDK#93]
Hi Guys,

I'm a maintiner of vcpkg team, we noticed the following error in building ms-glft on macOS with depending on latest rapidjson, it seems gltf-sdk use the old version of rapidjson? could you please help take a look? thank you! We found this issue when upgrade rapidjson to latest version.

Repro steps:
1. git clone https://github.com/alexander-smyslov/vcpkg
2. git checkout rapidjson01112021
3. ./bootstrap-vcpkg.bat
4. ./vcpkg install ms-glft

Failures:
```
/Users/vagrant/Data/buildtrees/ms-gltf/src/f2ebc72787-4b56b975bf.clean/GLTFSDK/Source/ExtensionsKHR.cpp:237:28: error: conversion from 'Microsoft::glTF::rapidjson::GenericValue<Microsoft::glTF::rapidjson::UTF8<>>::Object' (aka 'GenericObject<false, GenericValue<Microsoft::glTF::rapidjson::UTF8<>>>') to 'const rapidjson::Value' (aka 'const GenericValue<UTF8<>>') is ambiguous
    const rapidjson::Value sit = doc.GetObject();
                           ^     ~~~~~~~~~~~~~~~
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/rapidjson/document.h:872:5: note: candidate constructor
    GenericValue(Object o) RAPIDJSON_NOEXCEPT : data_(o.value_.data_) {
    ^
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/rapidjson/document.h:2956:5: note: candidate function
    operator ValueType&() const { return value_; }
    ^
/Users/vagrant/Data/buildtrees/ms-gltf/src/f2ebc72787-4b56b975bf.clean/GLTFSDK/Source/ExtensionsKHR.cpp:317:28: error: conversion from 'Microsoft::glTF::rapidjson::GenericValue<Microsoft::glTF::rapidjson::UTF8<>>::Object' (aka 'GenericObject<false, GenericValue<Microsoft::glTF::rapidjson::UTF8<>>>') to 'const rapidjson::Value' (aka 'const GenericValue<UTF8<>>') is ambiguous
    const rapidjson::Value objValue = doc.GetObject();
                           ^          ~~~~~~~~~~~~~~~
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/rapidjson/document.h:872:5: note: candidate constructor
    GenericValue(Object o) RAPIDJSON_NOEXCEPT : data_(o.value_.data_) {
    ^
/Users/vagrant/Data/installed/x64-osx/share/rapidjson/../../include/rapidjson/document.h:2956:5: note: candidate function
    operator ValueType&() const { return value_; }
    ^
```

**Comment by PolygonalSun** [comment]
Hey @PhoebeHui, I can probably take a look this week and see what's going on.

**Comment by bghgary** [comment]
@SergioRZMasson Can you take this one?

**Comment by SergioRZMasson** [comment]
@PhoebeHui , it seams that rapidJSON had a contract changes that are problematic on clang. I will be creating a PR with the fixes today.

**Comment by PhoebeHui** [comment]
Related to https://github.com/microsoft/glTF-SDK/pull/94

**Comment by SergioRZMasson** [comment]
@PhoebeHui , sorry for taking so long to get back to this issue. 

I've updated gltf sdk to use the latest version of rapidjson. However, it seems that the rapidjson that is currently available in vcpkg (commit ce81bc9edfe773667a7a4454ba81dac72ed4364c) has a serialization bug that is failing our validation tests (Our CI runs tests against glTF-SDK consuming rapidjson from vcpkg, that's why is currently broken). 

Running the tests locally using the latest version of rapidjson is working fine. Can you guys update rapidjson on vcpkg to the latest version? Otherwise, I will have to disable our tests to be able to merge the PR.

**Comment by PhoebeHui** [comment]
@SergioRZMasson, sorry for my late response, we have update to use gltf-sdk latest commit, which unblock the x64-osx triplet in vcpkg. thank you for your help!

**Comment by PhoebeHui** [comment]
@SergioRZMasson, sorry I missed this message! 

I have double checked, rapodjson has been updated to 232389d4f1012dddec4ef84861face2d2ba85709, see https://github.com/microsoft/vcpkg/blob/master/ports/rapidjson/portfile.cmake#L5.
